spring.application.name=backend

spring.datasource.url=${COMP307_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8081}

# Include the exception message in Spring Boot's default error JSON body.
# Without this, the "message" field is blank
server.error.include-message=always
